//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 09:27:09 PM MESZ 
//


package Aufgabe4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.chefkoch.rezepte._24641006006067.lenchen_s_schokoladenkuchen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.chefkoch.rezepte._24641006006067.lenchen_s_schokoladenkuchen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Kommentar }
     * 
     */
    public Recipe.Rezept.Kommentar createRecipeRezeptKommentar() {
        return new Recipe.Rezept.Kommentar();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Arbeitszeit }
     * 
     */
    public Recipe.Rezept.Arbeitszeit createRecipeRezeptArbeitszeit() {
        return new Recipe.Rezept.Arbeitszeit();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Titel.Bilder }
     * 
     */
    public Recipe.Rezept.Titel.Bilder createRecipeRezeptTitelBilder() {
        return new Recipe.Rezept.Titel.Bilder();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Brennwert }
     * 
     */
    public Recipe.Rezept.Brennwert createRecipeRezeptBrennwert() {
        return new Recipe.Rezept.Brennwert();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Titel }
     * 
     */
    public Recipe.Rezept.Titel createRecipeRezeptTitel() {
        return new Recipe.Rezept.Titel();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Zutaten }
     * 
     */
    public Recipe.Rezept.Zutaten createRecipeRezeptZutaten() {
        return new Recipe.Rezept.Zutaten();
    }

    /**
     * Create an instance of {@link Recipe.Rezept }
     * 
     */
    public Recipe.Rezept createRecipeRezept() {
        return new Recipe.Rezept();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Titel.Bilder.Bild }
     * 
     */
    public Recipe.Rezept.Titel.Bilder.Bild createRecipeRezeptTitelBilderBild() {
        return new Recipe.Rezept.Titel.Bilder.Bild();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Zubereitung }
     * 
     */
    public Recipe.Rezept.Zubereitung createRecipeRezeptZubereitung() {
        return new Recipe.Rezept.Zubereitung();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Zutaten.Zutat }
     * 
     */
    public Recipe.Rezept.Zutaten.Zutat createRecipeRezeptZutatenZutat() {
        return new Recipe.Rezept.Zutaten.Zutat();
    }

    /**
     * Create an instance of {@link Recipe.Rezept.Schwierigkeitsgrad }
     * 
     */
    public Recipe.Rezept.Schwierigkeitsgrad createRecipeRezeptSchwierigkeitsgrad() {
        return new Recipe.Rezept.Schwierigkeitsgrad();
    }

    /**
     * Create an instance of {@link Recipe }
     * 
     */
    public Recipe createRecipe() {
        return new Recipe();
    }

}
