//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 09:27:09 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.chefkoch.de/rezepte/24641006006067/Lenchen-s-Schokoladenkuchen.html", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Aufgabe4;
