//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 09:27:09 PM MESZ 
//


package Aufgabe4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rezept">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Titel">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Bilder">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Bild" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Zutaten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Zutat" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Menge" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Titel2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Arbeitszeit">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Schwierigkeitsgrad">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Brennwert">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Zubereitung">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Zubereitung" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Kommentar">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Bild" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Kommentar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rezept"
})
@XmlRootElement(name = "Recipe")
public class Recipe {

    @XmlElement(name = "Rezept", required = true)
    protected Recipe.Rezept rezept;

    /**
     * Gets the value of the rezept property.
     * 
     * @return
     *     possible object is
     *     {@link Recipe.Rezept }
     *     
     */
    public Recipe.Rezept getRezept() {
        return rezept;
    }

    /**
     * Sets the value of the rezept property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipe.Rezept }
     *     
     */
    public void setRezept(Recipe.Rezept value) {
        this.rezept = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Titel">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Bilder">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Bild" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Zutaten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Zutat" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Menge" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Titel2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Arbeitszeit">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Schwierigkeitsgrad">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Brennwert">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Zubereitung">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Zubereitung" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Kommentar">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Bild" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Kommentar" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titel",
        "zutaten",
        "titel2",
        "arbeitszeit",
        "schwierigkeitsgrad",
        "brennwert",
        "zubereitung",
        "kommentar"
    })
    public static class Rezept {

        @XmlElement(name = "Titel", required = true)
        protected Recipe.Rezept.Titel titel;
        @XmlElement(name = "Zutaten", required = true)
        protected Recipe.Rezept.Zutaten zutaten;
        @XmlElement(name = "Titel2", required = true)
        protected String titel2;
        @XmlElement(name = "Arbeitszeit", required = true)
        protected Recipe.Rezept.Arbeitszeit arbeitszeit;
        @XmlElement(name = "Schwierigkeitsgrad", required = true)
        protected Recipe.Rezept.Schwierigkeitsgrad schwierigkeitsgrad;
        @XmlElement(name = "Brennwert", required = true)
        protected Recipe.Rezept.Brennwert brennwert;
        @XmlElement(name = "Zubereitung", required = true)
        protected Recipe.Rezept.Zubereitung zubereitung;
        @XmlElement(name = "Kommentar", required = true)
        protected Recipe.Rezept.Kommentar kommentar;

        /**
         * Gets the value of the titel property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Titel }
         *     
         */
        public Recipe.Rezept.Titel getTitel() {
            return titel;
        }

        /**
         * Sets the value of the titel property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Titel }
         *     
         */
        public void setTitel(Recipe.Rezept.Titel value) {
            this.titel = value;
        }

        /**
         * Gets the value of the zutaten property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Zutaten }
         *     
         */
        public Recipe.Rezept.Zutaten getZutaten() {
            return zutaten;
        }

        /**
         * Sets the value of the zutaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Zutaten }
         *     
         */
        public void setZutaten(Recipe.Rezept.Zutaten value) {
            this.zutaten = value;
        }

        /**
         * Gets the value of the titel2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitel2() {
            return titel2;
        }

        /**
         * Sets the value of the titel2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitel2(String value) {
            this.titel2 = value;
        }

        /**
         * Gets the value of the arbeitszeit property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Arbeitszeit }
         *     
         */
        public Recipe.Rezept.Arbeitszeit getArbeitszeit() {
            return arbeitszeit;
        }

        /**
         * Sets the value of the arbeitszeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Arbeitszeit }
         *     
         */
        public void setArbeitszeit(Recipe.Rezept.Arbeitszeit value) {
            this.arbeitszeit = value;
        }

        /**
         * Gets the value of the schwierigkeitsgrad property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Schwierigkeitsgrad }
         *     
         */
        public Recipe.Rezept.Schwierigkeitsgrad getSchwierigkeitsgrad() {
            return schwierigkeitsgrad;
        }

        /**
         * Sets the value of the schwierigkeitsgrad property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Schwierigkeitsgrad }
         *     
         */
        public void setSchwierigkeitsgrad(Recipe.Rezept.Schwierigkeitsgrad value) {
            this.schwierigkeitsgrad = value;
        }

        /**
         * Gets the value of the brennwert property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Brennwert }
         *     
         */
        public Recipe.Rezept.Brennwert getBrennwert() {
            return brennwert;
        }

        /**
         * Sets the value of the brennwert property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Brennwert }
         *     
         */
        public void setBrennwert(Recipe.Rezept.Brennwert value) {
            this.brennwert = value;
        }

        /**
         * Gets the value of the zubereitung property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Zubereitung }
         *     
         */
        public Recipe.Rezept.Zubereitung getZubereitung() {
            return zubereitung;
        }

        /**
         * Sets the value of the zubereitung property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Zubereitung }
         *     
         */
        public void setZubereitung(Recipe.Rezept.Zubereitung value) {
            this.zubereitung = value;
        }

        /**
         * Gets the value of the kommentar property.
         * 
         * @return
         *     possible object is
         *     {@link Recipe.Rezept.Kommentar }
         *     
         */
        public Recipe.Rezept.Kommentar getKommentar() {
            return kommentar;
        }

        /**
         * Sets the value of the kommentar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Recipe.Rezept.Kommentar }
         *     
         */
        public void setKommentar(Recipe.Rezept.Kommentar value) {
            this.kommentar = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Arbeitszeit {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute
            protected Integer wert;
            @XmlAttribute(name = "Einheit")
            protected Integer einheit;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the wert property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWert() {
                return wert;
            }

            /**
             * Sets the value of the wert property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWert(Integer value) {
                this.wert = value;
            }

            /**
             * Gets the value of the einheit property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getEinheit() {
                return einheit;
            }

            /**
             * Sets the value of the einheit property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setEinheit(Integer value) {
                this.einheit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Brennwert {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute
            protected Integer wert;
            @XmlAttribute(name = "Einheit")
            protected Integer einheit;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the wert property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWert() {
                return wert;
            }

            /**
             * Sets the value of the wert property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWert(Integer value) {
                this.wert = value;
            }

            /**
             * Gets the value of the einheit property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getEinheit() {
                return einheit;
            }

            /**
             * Sets the value of the einheit property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setEinheit(Integer value) {
                this.einheit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Bild" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Datum" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Kommentar" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Kommentar {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected Integer id;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Bild")
            protected String bild;
            @XmlAttribute(name = "Datum")
            protected Integer datum;
            @XmlAttribute(name = "Kommentar")
            protected String kommentar;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the bild property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBild() {
                return bild;
            }

            /**
             * Sets the value of the bild property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBild(String value) {
                this.bild = value;
            }

            /**
             * Gets the value of the datum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDatum() {
                return datum;
            }

            /**
             * Sets the value of the datum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDatum(Integer value) {
                this.datum = value;
            }

            /**
             * Gets the value of the kommentar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKommentar() {
                return kommentar;
            }

            /**
             * Sets the value of the kommentar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKommentar(String value) {
                this.kommentar = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="wert" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Schwierigkeitsgrad {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute
            protected Integer wert;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the wert property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWert() {
                return wert;
            }

            /**
             * Sets the value of the wert property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWert(Integer value) {
                this.wert = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Bilder">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Bild" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bilder"
        })
        public static class Titel {

            @XmlElement(name = "Bilder", required = true)
            protected Recipe.Rezept.Titel.Bilder bilder;

            /**
             * Gets the value of the bilder property.
             * 
             * @return
             *     possible object is
             *     {@link Recipe.Rezept.Titel.Bilder }
             *     
             */
            public Recipe.Rezept.Titel.Bilder getBilder() {
                return bilder;
            }

            /**
             * Sets the value of the bilder property.
             * 
             * @param value
             *     allowed object is
             *     {@link Recipe.Rezept.Titel.Bilder }
             *     
             */
            public void setBilder(Recipe.Rezept.Titel.Bilder value) {
                this.bilder = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Bild" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bild"
            })
            public static class Bilder {

                @XmlElement(name = "Bild")
                protected List<Recipe.Rezept.Titel.Bilder.Bild> bild;

                /**
                 * Gets the value of the bild property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the bild property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getBild().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Recipe.Rezept.Titel.Bilder.Bild }
                 * 
                 * 
                 */
                public List<Recipe.Rezept.Titel.Bilder.Bild> getBild() {
                    if (bild == null) {
                        bild = new ArrayList<Recipe.Rezept.Titel.Bilder.Bild>();
                    }
                    return this.bild;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Bild {

                    @XmlValue
                    protected String value;
                    @XmlAttribute
                    protected Integer width;
                    @XmlAttribute
                    protected Integer height;
                    @XmlAttribute
                    protected String src;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the width property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getWidth() {
                        return width;
                    }

                    /**
                     * Sets the value of the width property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setWidth(Integer value) {
                        this.width = value;
                    }

                    /**
                     * Gets the value of the height property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getHeight() {
                        return height;
                    }

                    /**
                     * Sets the value of the height property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setHeight(Integer value) {
                        this.height = value;
                    }

                    /**
                     * Gets the value of the src property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSrc() {
                        return src;
                    }

                    /**
                     * Sets the value of the src property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSrc(String value) {
                        this.src = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Zubereitung" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Zubereitung {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Zubereitung")
            protected String zubereitung;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the zubereitung property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZubereitung() {
                return zubereitung;
            }

            /**
             * Sets the value of the zubereitung property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZubereitung(String value) {
                this.zubereitung = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Zutat" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Menge" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zutat"
        })
        public static class Zutaten {

            @XmlElement(name = "Zutat", required = true)
            protected List<Recipe.Rezept.Zutaten.Zutat> zutat;

            /**
             * Gets the value of the zutat property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the zutat property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getZutat().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Recipe.Rezept.Zutaten.Zutat }
             * 
             * 
             */
            public List<Recipe.Rezept.Zutaten.Zutat> getZutat() {
                if (zutat == null) {
                    zutat = new ArrayList<Recipe.Rezept.Zutaten.Zutat>();
                }
                return this.zutat;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Menge" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="Einheit" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Zutat {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Name")
                protected String name;
                @XmlAttribute(name = "Menge")
                protected Integer menge;
                @XmlAttribute(name = "Einheit")
                protected Integer einheit;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the menge property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getMenge() {
                    return menge;
                }

                /**
                 * Sets the value of the menge property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setMenge(Integer value) {
                    this.menge = value;
                }

                /**
                 * Gets the value of the einheit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getEinheit() {
                    return einheit;
                }

                /**
                 * Sets the value of the einheit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setEinheit(Integer value) {
                    this.einheit = value;
                }

            }

        }

    }

}
